server:
  applicationConnectors:
    - type: http
      port: 8083
  adminConnectors:
    - type: http
      port: 8084

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost/quizdb
  user: root
  password: root

viewRendererConfiguration:
  .mustache:
    cache: false